<%@ page language="java" contentType="text/html; charset=EUC-KR" pageEncoding="EUC-KR"%>
<%@ include file="/common/common.jsp"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<jsp:include page="/head.jsp" flush="false" />

	<style type="text/css">
		label {margin-right:20px;}
		
input[type=checkbox].css-checkbox {
 position: absolute; 
 overflow: hidden; 
 clip: rect(0 0 0 0); 
 height:1px; 
 width:1px; 
 margin:-1px; 
 padding:0;
 border:0;
 }

 input[type=checkbox].css-checkbox + label.css-label {
 padding-left:20px;
 height:15px; 
 display:inline-block;
 line-height:15px;
 background-repeat:no-repeat;
 background-position: 0 0;
 font-size:15px;
 vertical-align:middle;
 cursor:pointer;
 }

 input[type=checkbox].css-checkbox:checked + label.css-label {
 background-position: 0 -15px;
 }

 .css-label{
 background-image:url(./images/dark-check-green.png);
 }
	</style>
</head>
<body>
					<input id="demo_box_1" class="css-checkbox" type="checkbox" />
					<label for="demo_box_1" name="demo_lbl_1" class="css-label">Option #1</label>
					<!-- Checkbox powered by CssCheckbox.com -->
					
					<input id="demo_box_2" class="css-checkbox" type="checkbox" checked="checked" />
					<label for="demo_box_2" name="demo_lbl_2" class="css-label">Selected Option</label>
					<!-- Checkbox powered by CssCheckbox.com -->
					
					<input id="demo_box_3" class="css-checkbox" type="checkbox" />
					<label for="demo_box_3" name="demo_lbl_3" class="css-label">Option #3</label>
					<!-- Checkbox powered by CssCheckbox.com -->
						</p>
		<p style="padding-left:25px;">Checkbox generated by <a href="http://csscheckbox.com">CSS Checkbox</a></p>
		</body>
		</html>